version: '3'
services:
  student_service:
    image: scorpion0206/student_service
    restart: unless-stopped
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017
    ports:
      - "127.0.0.1:8080:8080"

  mongo:
    restart: unless-stopped
    image: mongo:4
    hostname: mongo
    ports:
      - "127.0.0.1:27017:27017"